title: NZ Retirement Village Data
author: Avi

execute:
  execute_notebooks: 'off'

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/avivajpeyi/nz_retirement_webscraper
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
